import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.infoMain}>
          <div className={styles.lightBlueBubble}>
            <h2 className={styles.bubbleTitle}>
              Main Title
            </h2>
            <p className={styles.lightTextForBubble}>
              text in
            </p>
          </div>
        </div>

        <div className={styles.info2}>
          <div className={styles.info2Bubble}>
            <h2 className={styles.info2BubbleTitle}>
              Main Title
            </h2>
            <p className={styles.info2BubbleP}>
              text in
            </p>
          </div>

          <div className={styles.info2Bubble}>
            <h2 className={styles.info2BubbleTitle}>
              Main Title
            </h2>
            <p className={styles.info2BubbleP}>
              text in
            </p>
          </div>

          <div className={styles.info2Bubble}>
            <h2 className={styles.info2BubbleTitle}>
              Main Title
            </h2>
            <p className={styles.info2BubbleP}>
              text in
            </p>
          </div>
        </div>


        <div className={styles.skillSection}>
          <div className={styles.skillBubble}>
            <h2 className={styles.skillTitle}>
              Main Title
            </h2>
            <p className={styles.skillBubbleText}>
              text in
            </p>
          </div>

          <div className={styles.skillBubble}>
            <h2 className={styles.skillTitle}>
              Main Title
            </h2>
            <p className={styles.skillBubbleText}>
              text in
            </p>
          </div>

          <div className={styles.skillBubble}>
            <h2 className={styles.skillTitle}>
              Main Title
            </h2>
            <p className={styles.skillBubbleText}>
              text in
            </p>
          </div>

          <div className={styles.skillBubble}>
            <h2 className={styles.skillTitle}>
              Main Title
            </h2>
            <p className={styles.skillBubbleText}>
              text in
            </p>
          </div>

          <div className={styles.skillBubble}>
            <h2 className={styles.skillTitle}>
              Main Title
            </h2>
            <p className={styles.skillBubbleText}>
              text in
            </p>
          </div>

          <div className={styles.skillBubble}>
            <h2 className={styles.skillTitle}>
              Main Title
            </h2>
            <p className={styles.skillBubbleText}>
              text in
            </p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
