import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.infoMain}>
          <div className={styles.lightBlueBubble}>
            <h2 className={styles.bubbleTitle}>
              You have an idea.
            </h2>
            <p className={styles.lightTextForBubble}>
              We turn your ideas into tangible things and reduce the time it takes for customers to find, buy, engage with, and share your product or idea.
            </p>
          </div>
        </div>

        <div className={styles.info2}>
          <div className={styles.info2Bubble}>
            <h2 className={styles.info2BubbleTitle}>
              Experience
            </h2>
            <p className={styles.info2BubbleP}>
              We've seen a variety of processes, products, technologies. From Mobile to Games to Website.
            </p>
          </div>

          <div className={styles.info2Bubble}>
            <h2 className={styles.info2BubbleTitle}>
              Skill
            </h2>
            <p className={styles.info2BubbleP}>
              Our technologies are listed. But they're not limited. We're constantly improving.
            </p>
          </div>

          <div className={styles.info2Bubble}>
            <h2 className={styles.info2BubbleTitle}>
              MDM/Enterprise Ability
            </h2>
            <p className={styles.info2BubbleP}>
              Our owner used to maintain enterprise apps used by govt. and major players. We cand integrate MDM and similar into your apps.
            </p>
          </div>
        </div>


        <div className={styles.skillSection}>
          <div className={styles.skillBubble}>
            <h2 className={styles.skillTitle}>
              iOS (iPhone)
            </h2>
            <p className={styles.skillBubbleText}>
              Our home/wheelhouse has been iOS apps for over 11+ yrs. Swift and Objective-C + Flutter.
            </p>
          </div>

          <div className={styles.skillBubble}>
            <h2 className={styles.skillTitle}>
              Unity
            </h2>
            <p className={styles.skillBubbleText}>
              We've actually worked on Unity under contract for Seattle businesses. Now we do it for you.
            </p>
          </div>

          <div className={styles.skillBubble}>
            <h2 className={styles.skillTitle}>
              Android
            </h2>
            <p className={styles.skillBubbleText}>
              Let's get your Android app going, native or cross-platform using Flutter and React Native if you wish.
            </p>
          </div>

          <div className={styles.skillBubble}>
            <h2 className={styles.skillTitle}>
              React Native
            </h2>
            <p className={styles.skillBubbleText}>
              We recommend not doing this, but if you have a React Native app or a simple idea that doesn't need anything specially designed, it's a good tool.
            </p>
          </div>

          <div className={styles.skillBubble}>
            <h2 className={styles.skillTitle}>
              Flutter
            </h2>
            <p className={styles.skillBubbleText}>
              If you want a cross-platform app that doesn't sacrifice battery or performance the same way other tools do, we recommend Flutter.
            </p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
